#try - exeption

try:
    print(Hello)
except Exception as e:
    print("Something went wrong")
    print(e)

finally:
    print("END")